module.exports = {
    "gj": {code: "100000", name: "最高人民检察院", channelWebPath: "/gj"},
    "bj": {code: "110000c", name: "北京", channelWebPath: "/gj/bj"},
    "tj": {code: "120000c", name: "天津", channelWebPath: "/gj/tj"},
    "heb": {code: "130000c", name: "河北", channelWebPath: "/gj/heb"},
    "sxa": {code: "140000c", name: "山西", channelWebPath: "/gj/sxa"},
    "nmg": {code: "150000c", name: "内蒙古", channelWebPath: "/gj/nmg"},
    "ln": {code: "210000c", name: "辽宁", channelWebPath: "/gj/ln"},
    "jl": {code: "220000c", name: "吉林", channelWebPath: "/gj/jl"},
    "hlj": {code: "230000c", name: "黑龙江", channelWebPath: "/gj/hlj"},
    "sh": {code: "310000c", name: "上海", channelWebPath: "/gj/sh"},
    "js": {code: "320000c", name: "江苏", channelWebPath: "/gj/js"},
    "zj": {code: "330000c", name: "浙江", channelWebPath: "/gj/zj"},
    "ah": {code: "340000c", name: "安徽", channelWebPath: "/gj/ah"},
    "fj": {code: "350000c", name: "福建", channelWebPath: "/gj/fj"},
    "jx": {code: "360000c", name: "江西", channelWebPath: "/gj/jx"},
    "sd": {code: "370000c", name: "山东", channelWebPath: "/gj/sd"},
    "hen": {code: "410000c", name: "河南", channelWebPath: "/gj/hen"},
    "hub": {code: "420000c", name: "湖北", channelWebPath: "/gj/hub"},
    "hun": {code: "430000c", name: "湖南", channelWebPath: "/gj/hun"},
    "gd": {code: "440000c", name: "广东", channelWebPath: "/gj/gd"},
    "gx": {code: "450000c", name: "广西", channelWebPath: "/gj/gx"},
    "han": {code: "460000c", name: "海南", channelWebPath: "/gj/han"},
    "cq": {code: "500000c", name: "重庆", channelWebPath: "/gj/cq"},
    "sc": {code: "510000c", name: "四川", channelWebPath: "/gj/sc"},
    "gz": {code: "520000c", name: "贵州", channelWebPath: "/gj/gz"},
    "yn": {code: "530000c", name: "云南", channelWebPath: "/gj/yn"},
    "xz": {code: "540000c", name: "西藏", channelWebPath: "/gj/xz"},
    "sxb": {code: "610000c", name: "陕西", channelWebPath: "/gj/sxb"},
    "gs": {code: "620000c", name: "甘肃", channelWebPath: "/gj/gs"},
    "qh": {code: "630000c", name: "青海", channelWebPath: "/gj/qh"},
    "nx": {code: "640000c", name: "宁夏", channelWebPath: "/gj/nx"},
    "xj": {code: "650000c", name: "新疆", channelWebPath: "/gj/xj"},
    "jsbt": {code: "660000c", name: "兵团", channelWebPath: "/gj/jsbt"}
};

